url: http://citrusdeer.com

# Site settings
title: Citrus Deer
email: skylerr.curtis@gmail.com
description: "A Specialized Services company"

# Team names, titles and social links
people:
- name: Skyler Curtis
  pic: skyler
  position: Security Researcher/Co-Founder
  social:
    - title: github
      url: https://github.com/deadPix3l

services:
- name: Custom Development
  icon: fa-code
  description: developers skilled in 13+ languages counting
- name: Penetration Testing
  icon: fa-shield-halved
  description: Physical or Digital, we'll get in!
- name: Blockchain
  icon: "fa-brands fa-ethereum"
  description: develop dapps, new tokens, web3 gaming, etc
- name: Cloud, DevOps, Infrastructure
  icon: "fa-solid fa-cloud"
  description: It's just someone elses computer
- name: Data Science
  icon: fa-flask
  description: Crunching the numbers

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/citrusdeer


# Build settings
markdown: kramdown
permalink: pretty

